services:
  backend:
    image: maven:3.9.4-eclipse-temurin-21
    working_dir: /app
    volumes:
      - ./back:/app
    ports:
      - "1234:1234"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vlc
      SPRING_DATASOURCE_USERNAME: vlc
      SPRING_DATASOURCE_PASSWORD: vlc
      SPRING_PROFILES_ACTIVE: dev
    command: mvn spring-boot:run -Dspring-boot.run.fork=false
    depends_on:
      - db

  front:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "4321:5173"
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: '1000'
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - backend
