services:
  db:
    image: postgis/postgis:14-3.3
    environment:
      POSTGRES_DB: vlc
      POSTGRES_USER: vlc
      POSTGRES_PASSWORD: vlc
    ports:
      - "6543:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./back/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./back/src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    ports:
      - "1234:1234"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vlc
      SPRING_DATASOURCE_USERNAME: vlc
      SPRING_DATASOURCE_PASSWORD: vlc
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db

  
  front:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "4321:5173"
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: '1000'
    command: sh -c "npm install --legacy-peer-deps && npm install --save-dev @types/react @types/react-dom && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - backend

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    volumes:
      - ./mobile:/app
      - /app/node_modules
    ports:
      - "9876:8100"
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    depends_on:
      - backend
    
  tileserver:
    image: maptiler/tileserver-gl:latest
    volumes:
      - ./maps:/data 
    ports:
      - "8081:8080"
    command: ["--mbtiles", "/data/osm-2020-02-10-v3.11_madagascar_antananarivo.mbtiles"]

volumes:
  db_data:
  m2:
