services:

  # ==========================
  # DATABASE
  # ==========================
  db:
    image: postgis/postgis:14-3.3
    container_name: vlc_db
    environment:
      POSTGRES_DB: vlc
      POSTGRES_USER: vlc
      POSTGRES_PASSWORD: vlc
    ports:
      - "6543:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./back/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./back/src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro

  # ==========================
  # BACKEND SPRING
  # ==========================
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: vlc_backend
    volumes:
      - ./back:/app
    ports:
      - "1234:1234"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vlc
      SPRING_DATASOURCE_USERNAME: vlc
      SPRING_DATASOURCE_PASSWORD: vlc
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db

  # ==========================
  # FRONT REACT
  # ==========================
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: vlc_front
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "4321:80"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
      - maps_server

  # ==========================
  # MOBILE (Vue / Ionic)
  # ==========================
  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    container_name: vlc_mobile
    volumes:
      - ./mobile:/app
      - /app/node_modules
    ports:
      - "9876:8100"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

  # ==========================
  # MAP DATA IMPORT (RUN ONCE)
  # ==========================
  map_import:
    image: openmaptiles/import-data
    container_name: vlc_map_import
    volumes:
      - maps_data:/data
    environment:
      DOWNLOAD_PBF: https://download.geofabrik.de/africa/madagascar-latest.osm.pbf

  # ==========================
  # MAP SERVER (OFFLINE)
  # ==========================
  maps_server:
    image: klokantech/tileserver-gl
    container_name: signalement_maps
    ports:
      - "8081:80"
    volumes:
      - maps_data:/data
    restart: unless-stopped
    depends_on:
      - map_import

# ==========================
# VOLUMES
# ==========================
volumes:
  db_data:
  maps_data:
  m2:
